Add /credit_card/country input
maxmind/minfraud-api-dotnet pull request #137
Opened 2022-03-07 22:41 UTC by oschwald

2022-03-08 19:08 UTC, FreeKitty submitted a review, later dismissed

2022-03-08 22:04 UTC, horgh requested changes

2022-03-08 22:04 UTC, horgh commented on MaxMind.MinFraud/Request/CreditCard.cs
> +        /// located.This may be passed instead of <c>IssuerIdNumber</c> if you
"located. This"

2022-03-08 22:04 UTC, horgh commented on MaxMind.MinFraud/Request/CreditCard.cs
> +        /// Construct for binary compatibility.
"Constructor"?

2022-03-08 22:04 UTC, horgh commented on MaxMind.MinFraud/Request/CreditCard.cs
> +        /// The country where the issuer of the card is located.This may be
"located. This"

2022-03-09 16:14 UTC, horgh approved these changes

2022-03-09 16:14 UTC, merged