Add info about how to use the Sandbox environment
maxmind/minfraud-api-dotnet pull request #187
Opened 2023-08-10 17:40 UTC by faktas2

- Add info on how to use the `host` parameter.

2023-08-11 17:25 UTC, horgh requested changes

2023-08-11 17:25 UTC, horgh commented on README.md
> +var client = new WebServiceClient(10, "LICENSEKEY", host = 'sandbox.maxmind.com');
Did you intend to change this line?

2023-08-11 17:31 UTC, faktas2 commented on README.md
> +var client = new WebServiceClient(10, "LICENSEKEY", host = 'sandbox.maxmind.com');
No sorry about that.

2023-08-14 15:35 UTC, horgh approved these changes

2023-08-14 15:35 UTC, merged